### ISSUE TITLE
guided tour problem in vignette

### ISSUE THREAD

**Issue by uschiLaa** [uschiLaa/tourr#1]
The tourr.Rmd vignette does not build, with error indicating an issue with the "<<-" assignment of "index" in the guided tour code, see error message below. @huizezhang-sherry @sa-lee

> devtools::build_vignettes()
Building tourr vignettes
--- re-building ‘edges.Rmd’ using rmarkdown
--- finished re-building ‘edges.Rmd’

--- re-building ‘tourr.Rmd’ using rmarkdown
Quitting from lines 58-61 (tourr.Rmd) 
Error: processing vignette 'tourr.Rmd' failed with diagnostics:
cannot change value of locked binding for 'index'
--- failed re-building ‘tourr.Rmd’

SUMMARY: processing the following file failed:
  ‘tourr.Rmd’

Error : Vignette re-building failed.
In addition: Warning message:
In tools::buildVignettes(dir = pkg_path, clean = clean, tangle = TRUE,  :
  Files named as vignettes but with no recognized vignette engine:
   ‘vignettes/global-structure.Rmd’
(Is a VignetteBuilder field missing?)
Error: callr subprocess failed: Vignette re-building failed.
Type .Last.error.trace to see where the error occured

**Comment by huizezhang-sherry** [comment]
I tried to set `error = TRUE` in `knitr::opts_chunk$set()` as per Yihui's comment on https://groups.google.com/g/knitr/c/_KQRjcEMAQs and it builts.
